// Generates src/static.ts — the built SPA inlined as base64 so the Worker can
// serve it without an ASSETS binding (deployed environments where the assets
// upload API isn't reachable).
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const DIST = new URL("../web/dist/", import.meta.url).pathname;
const CT = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css",
  ".js": "application/javascript",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".webmanifest": "application/manifest+json",
  ".json": "application/json",
  ".txt": "text/plain",
  ".woff2": "font/woff2",
};

const files = [];
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else files.push(p);
  }
})(DIST);

const entries = files
  .sort()
  .map((p) => {
    const rel = "/" + relative(DIST, p);
    const ext = p.slice(p.lastIndexOf("."));
    const b64 = readFileSync(p).toString("base64");
    return `  ${JSON.stringify(rel)}: { type: ${JSON.stringify(
      CT[ext] ?? "application/octet-stream"
    )}, body: ${JSON.stringify(b64)} },`;
  })
  .join("\n");

writeFileSync(
  new URL("../src/static.ts", import.meta.url),
  `// AUTO-GENERATED by scripts/gen-static.mjs — do not edit by hand.
export const STATIC_FILES: Record<string, { type: string; body: string }> = {
${entries}
};
`
);
console.log(`inlined ${files.length} assets`);
